#ifndef OFFERAUDIODATA_GLOBAL_H
#define OFFERAUDIODATA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OFFERAUDIODATA_LIBRARY)
#  define OFFERAUDIODATASHARED_EXPORT Q_DECL_EXPORT
#else
#  define OFFERAUDIODATASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OFFERAUDIODATA_GLOBAL_H
